exec-once = gentoo-pipewire-launcher

exec-once = pkill -f xdg-desktop-portal

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = [[ -z "$DBUS_SESSION_BUS_ADDRESS" ]] && eval $(dbus-launch --sh-syntax)

exec-once = sleep 2 && /usr/libexec/xdg-desktop-portal --replace
exec-once = sleep 3 && /usr/libexec/xdg-desktop-portal-hyprland

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = ~/.config/hypr/scripts/xdp-hypr

exec-once = hyprctl setcursor Bibata-Modern-Ice 14
exec-once = waybar
exec-once = hyprpaper
exec-once = syncthing

