# Nord Colorscheme for Kitty
# Based on:
# - https://gist.github.com/marcusramberg/64010234c95a93d953e8c79fdaf94192
# - https://github.com/arcticicestudio/nord-hyper

foreground            #F1E4C2
background            #131515
selection_foreground  #131515
selection_background  #F1E4C2
url_color             #ef944d
cursor                #F1E4C2

# black
color0      #1f2223
color8      #393939

# red
color1      #f16e65
color9      #ef958f

# green
color2      #7dc97d
color10     #a4daa4

# yellow
color3      #ef944d
color11     #efbe71

# blue
color4      #8dacbb
color12     #bfd0d9

# magenta
color5      #e28dc6
color13     #ebadd6

# cyan
color6      #7dc9a3
color14     #abd4bf

# white
color7      #e0ce9e
color15     #F1E4C2
