term=foot

title=feet

font=ProFont IIx Nerd Font:size=16
font=JetBrains Mono NF Medium:size=16
font=MapleMono NF Medium:size=16

[cursor]
# style=block
# blink=no
# blink-rate=500
# beam-thickness=1.5
# underline-thickness=<font underline thickness>

[colors]
alpha=0.9
background=131515
foreground=F1E4C2

# black
regular0 = 1f2223
bright0  = 393939

# red
regular1 = f16e65
bright1  = ef958f

# green
regular2 = 7dc97d
bright2  = a4daa4

# yellow
regular3 = ef944d
bright3  = efbe71

# blue
regular4 = 8dacbb
bright4  = bfd0d9

# magenta
regular5 = e28dc6
bright5  = ebadd6

# cyan
regular6 = 7dc9a3
bright6  = abd4bf

# white
regular7 = e0ce9e
bright7  = F1E4C2
