term=foot

title=feet

font=ProFont IIx Nerd Font:size=12
font=MapleMono NF Medium:size=16
font=Cartograph Mono CF:size=14
font=JetBrains Mono NF:size=14
font=CaskaydiaCove NF:size=14

pad=8x8

dpi-aware=yes

[cursor]
# style=block
# blink=no
# blink-rate=500
# beam-thickness=1.5
# underline-thickness=<font underline thickness>

[colors]
alpha=0.9
background=141515
foreground=f4decd

# black
regular0 = 1e1f1e
bright0  = 3b403c

# red
regular1 = f16e65
bright1  = ef968f

# green
regular2 = 7ec97e
bright2  = a4daa4

# yellow
regular3 = ef934d
bright3  = f4b585

# blue
regular4 = 71b4d6
bright4  = b0d4e8

# magenta
regular5 = e28dc6
bright5  = ebadd6

# cyan
regular6 = 7ec9a3
bright6  = abd4bf

# white
regular7 = d9cdb5
bright7  = f4decd
